### ISSUE TITLE
argon2 initializer 

### ISSUE THREAD

**Issue by ghz-max** [alexandrevicenzi/unchained#11]
Hi !

First, thanks for the library! Really helping me to migrate from django.

Looking at your argon2 implementation I noticed the default initializer doesn't use the recommanded minimal values :

```
// NewArgon2Hasher secures password hashing using the argon2 algorithm.
func NewArgon2Hasher() *Argon2Hasher {
	return &Argon2Hasher{
		Algorithm: "argon2",
		Time:      2,
		Memory:    512,
		Threads:   2,
		Length:    16,
	}
}
```

https://pkg.go.dev/golang.org/x/crypto/argon2#Key

The draft RFC recommends[2] time=3, and memory=32*1024 is a sensible number. If using that amount of memory (32 MB) is not possible in some contexts then the time parameter can be increased to compensate.

Is there a reason behind your time=2 and memory=512?

**Comment by alexandrevicenzi** [comment]
Hi,

Yes, it's the value used in Django 3.1, you can check [here](https://github.com/django/django/blob/3.1/django/contrib/auth/hashers.py#L293).

You can still initialize your own custom `Argon2Hasher` with parameters that you need, but you will just lose some of the generic helper's functions.

**Comment by ghz-max** [comment]
Thanks for the reply and the provided rational!

Kinda pity Django isn't following the recommendations.

Regarding a custom Argon2Hasher, thankfully you made public the parameters. Hence, something like this should work without losing the generic helper's functions but losing the Django compatibility:

```
a := argon2.NewArgon2Hasher()
a.Time = 3
a.Memory = 32 * 1024
a.Verify(password, encoded)
```

Closing the issue.

**Comment by alexandrevicenzi** [comment]
You can make it simpler as:

```go
a := &Argon2Hasher{
  Algorithm: "argon2",
  Time:      3,
  Memory:    32 *1024,
  Threads:   2,
  Length:    16,
}
```
