### ISSUE TITLE
Implement bcrypt hasher

### ISSUE THREAD

**Issue by alexandrevicenzi** [alexandrevicenzi/unchained#2]
Implement bcrypt and bcrypt_sha256 hashers.

**Comment by vijeth-aradhya** [comment]
@alexandrevicenzi Should we have to use Go for the implementation?

**Comment by alexandrevicenzi** [comment]
@vijeth-aradhya I think https://godoc.org/golang.org/x/crypto/bcrypt solve this problem. It's from golang, but not in the std lib.

The bcrypt must match the Django implementation.

Django source:

- [BCryptSHA256PasswordHasher](https://github.com/django/django/blob/master/django/contrib/auth/hashers.py#L401)
- [BCryptPasswordHasher](https://github.com/django/django/blob/master/django/contrib/auth/hashers.py#L465)
