### ISSUE TITLE
PBKDF2 override default number of iterations

### ISSUE THREAD

**Issue by besedad** [alexandrevicenzi/unchained#6]
Right now, there's no way to change default number of iterations for PBKDF2 without using the underlying package directly. Could that be changed?

**Comment by alexandrevicenzi** [comment]
No. This is based on Django parameters, unless they change it's supposed to be the same value.

Maybe you could explain your use case and provide a sample code example? We may find an alternative solution or include more methods into this library.

**Comment by besedad** [comment]
The use case is to adjust the difficulty/speed of hashing. Right now this value is hard-coded to 180000 iterations. In the future higher values will be recommended (for reference, in year 2000 the recommended value was 1000 iterations[0]). We don't want to rely on this value to be updated by the library's maintainer, that is by you, and be forced to update the package to account for this change.

My idea is to add supplementary function `MakePasswordWithConfig(password, salt string, config *Config)` where config is:

```
type Config struct {
    Hasher string
    Iterations int
    // Add other overrides for default values (i.e. DefaultSaltSize,...)
}
```
This shouldn't break compatiblity with packages that already use unchained.

**Comment by alexandrevicenzi** [comment]
Adding an extra method is a solution, but the underlying packages do not follow the same parameters, and this Config object would be weird if it hold all parameters. Config parameter could be an interface and the object type changes based on the Hasher used.

What's the problem using the underlying package itself?

**Comment by besedad** [comment]
> What's the problem using the underlying package itself?

There's no problem, it's more of a matter of convenience.

**Comment by alexandrevicenzi** [comment]
@besedad you can send a PR with a proposal if you want, this feature might be interesting.

**Comment by alexandrevicenzi** [comment]
Closing as there's no clear way of fixing this and/or interest. Feel free to re-open in the future.
