### ISSUE TITLE
Release a 1.0.0 version

### ISSUE THREAD

**Issue by dimiro1** [alexandrevicenzi/unchained#8]
What do you think about releasing a v1.0.0 version of the library?

**Comment by alexandrevicenzi** [comment]
@dimiro1 What do you mean by releasing? Just create a git tag? If that, probably can be easily done, but 1.0 is long gone. This lib is more to 1.something right now.

**Comment by dimiro1** [comment]
Exactly just create a tag.

**Comment by alexandrevicenzi** [comment]
@dimiro1 v1.2.0 is the latest one. Based on commit history we can split intro 3 "released" versions.

**Comment by dimiro1** [comment]
Thanks a lot @alexandrevicenzi
