### ISSUE TITLE
Non cryptographic use of rand.Intn

### ISSUE THREAD

**Issue by davidcroda** [alexandrevicenzi/unchained#9]
Maybe it's not an issue, but shouldn't the [GetRandomString](https://github.com/alexandrevicenzi/unchained/blob/694e8b1c5d50ec84eff94910f6826570625e2787/unchained.go#L55) function used to generate salts be using a cryptographic random number generator rather then math/rand? ie. https://golang.org/pkg/crypto/rand/#Int

**Comment by alexandrevicenzi** [comment]
@davidcroda I believe it's safe to change, I borrowed this function from Django source code and just made the same version in Go.
